<?php

namespace App\Http\Controllers;

use Symfony\Component\HttpFoundation\BinaryFileResponse;

/**
 * Serves tenant files without turning the tenant storage tree into a public
 * directory. Clinic brand assets are deliberately public; clinical uploads
 * require a short-lived signed URL generated by the Image model.
 */
class TenantFileController extends Controller
{
    public function public(string $tenant, string $path): BinaryFileResponse
    {
        if (!str_starts_with($path, 'clinic-logos/') && !str_starts_with($path, 'clinic-hero/')) {
            abort(404);
        }

        return $this->serve($tenant, $path, 'public, max-age=31536000, immutable');
    }

    public function private(string $tenant, string $path): BinaryFileResponse
    {
        return $this->serve($tenant, $path, 'private, no-store');
    }

    private function serve(string $tenant, string $path, string $cacheControl): BinaryFileResponse
    {
        if (str_contains($tenant, ['/', '\\', "\0"]) || str_contains($path, ['..', '\\', "\0"])) {
            abort(404);
        }

        $root = realpath(storage_path('tenant' . $tenant . '/app/public'));
        $file = $root ? realpath($root . DIRECTORY_SEPARATOR . $path) : false;

        if (!$root || !$file || !str_starts_with($file, $root . DIRECTORY_SEPARATOR) || !is_file($file)) {
            abort(404);
        }

        return response()->file($file, [
            'Cache-Control' => $cacheControl,
            'Content-Type' => mime_content_type($file) ?: 'application/octet-stream',
            'X-Content-Type-Options' => 'nosniff',
        ]);
    }
}
